import { AppBar, Container, Toolbar, Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import PersonPanel from "src/components/PersonPanel";

const Home: NextPage = () => {
    
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <AppBar position="sticky">
                <Toolbar>
                    <Typography variant="h2">Emplotree</Typography>
                </Toolbar>
            </AppBar>

            <Container>
                <PersonPanel person={{id: "jeff", name: "Jeff", infoComplete: false}}/>
            </Container>
        </div>
    );
};

export default Home;
